### ISSUE TITLE
Spamming the vote/unvote button

### ISSUE THREAD

**Issue by zachjbrowning** [Gribbenator/subcomp#1]
Vote button seems to just increment/decrement the total vote count for a project rather than link a person's vote explicitly to another person's project. This means spamming the vote/unvote button (i.e. sending a POST to /api/vote multiple times) submits the vote multiple times. Seems to only occur when decrementing hence why someone has -2 votes (sorry I tried to rectify it by spamming vote but it didn't work...). 

Apologies for breaking btw - genuinely didn't mean to. Before I stuffed it up there was 0 votes for tabs collage.

CORRECTION : -ve votes appear to only have been a frontend state management issue but idk anymore because more people have voted i think...

**Comment by piddlingtuna** [comment]
I've had a look at the database and it's definitely a frontend state issue. I'll fix it.

**Comment by piddlingtuna** [comment]
Ok the actual problem was that the backend wasn't returning an error messaged if it detected duplicate vote/unvote. Should be fixed. Let me know if it persists.
